# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Tests

on:
  push:
    branches:
      - master
      - trunk-v*
  pull_request:
    branches:
      - master
      - trunk-v*
    paths:
      - '*.js'
      - 'src/*'
      - 'test/*'
      - 'package.json'

jobs:
  tests:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        node-version: [8.9.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2.1.0
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/cache@v1
      id: cache-node-modules
      with:
        path: node_modules
        key: ${{ matrix.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ matrix.os }}-node-${{ matrix.node-version }}-
    - run: npm install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
    - run: npm test -- --coverage
      env:
        CI: true
    - name: Report coverage
      if: success()
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./test/.coverage/lcov.info
